# To launch locally and display draft documents
#
#   hugo server -D
#
baseurl = "https://javapirates.netlify.com"
title = "Portland Java Pirates"
copyright = "Copyright © 2018–2019 Portland Java Pirates"
theme = "jeffprod"
googleAnalytics = "UA-131409351-1"
enableGitInfo = true
paginate = 10
summaryLength = 40

# this causes the full domain name to be prepended when using 'relURL' in templates
#canonifyurls = true


[params]
    course_title = "TBD"
    course_url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

    header_image = "/img/laptop-python-books.jpg"

    # default preview information displayed in Slack and Twitter links
    preview_image = "/img/java/java-og-preview.jpg"
    preview_description = "It's Java time! Dust off your Design Patterns books, fire up the AbstractFactoryBeans, and get ready for some industrial strength programming! We're making the switch to Java!"

    meetup_url = "https://www.meetup.com/Portland-Python-Pirates/"
    slack_group = "pythonpirates"
    slack_url = "https://pythonpirates.slack.com"
    slack_join_request_url = "https://join.slack.com/t/pythonpirates/shared_invite/enQtNDYyMjg5NzEyMzM2LTlhNjAxYjJiOTVkYjA2ODE3MDc0ZTQ1YmQ2YWEwODJlZTIwY2Y5YmUzYjNhNDIxMTlhYWJjZGYwNWU5MzVkYmI"
    github_url = "https://github.com/PDXPythonPirates"
    include_toc = false

    # this toggles display of the urgent banner text at the top of all pages
    # individual pages can disable this with the page front matter 'display_urgent: false'
    display_urgent = true

    # this overrides the header image for all pages;  comment out to disable
    urgent_header_image = "/img/java/java-header.jpg"

    urgent_url = "/java/"
    # text displayed in top page nav; unset this to remove
    #urgent_nav_title = "Java"
    # link text displayed in banner box at the top of content section
    urgent_link_title = "Meetup Switching Focus to Java"
    urgent_date = "2019-04-01"

[taxonomies]
    tag = "tags"
    archive = "archives"

